apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: credential-dumping-detection
spec:
  kprobes:
    - call: "sys_execve"
      args:
        - index: 0
          type: "filename"
          
    - call: "sys_openat"
      args:
        - index: 1
          type: "path"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Prefix" # Vérifiez si votre CRD accepte "Prefix" ou "Equal"
              values:
                - "/etc/shadow"
                - "/etc/gshadow"
                - "/var/lib/postgresql"

    - call: "sys_ptrace"
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"

    - call: "sys_process_vm_readv"
      args:
        - index: 0
          type: "int"

    - call: "sys_open"
      args:
        - index: 0
          type: "path"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Suffix" # "PostFix" est remplacé par "Suffix"
              values:
                - "/mem"
                - "/maps"
